version: "3.9"
services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - "27017:27017"

  ratus:
    image: hyperonym/ratus:0.4.0
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ENGINE: "mongodb"
      MONGODB_URI: "mongodb://mongo:27017"
      MONGODB_DATABASE: "ratus"
      MONGODB_COLLECTION: "tasks"
      MONGODB_RETENTION_PERIOD: "72h"
    ports:
      - "8000:80"
