version: "3.9"
services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - "27017:27017"

  ratus:
    image: hyperonym/ratus:0.4.0
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ENGINE: "mongodb"
      MONGODB_URI: "mongodb://mongo:27017"
      MONGODB_DATABASE: "ratus"
      MONGODB_COLLECTION: "tasks"
      MONGODB_RETENTION_PERIOD: "72h"
    ports:
      - "8000:80"

  prometheus:
    image: prom/prometheus:v2.38.0
    restart: unless-stopped
    depends_on:
      - ratus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.time=30d"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.1.5
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
