version: "3.9"
services:
  mongodb-sharded:
    image: bitnami/mongodb-sharded:4.4
    restart: unless-stopped
    depends_on:
      - mongodb-shard0
      - mongodb-cfg
    environment:
      MONGODB_ADVERTISED_HOSTNAME: "mongodb-sharded"
      MONGODB_SHARDING_MODE: "mongos"
      MONGODB_CFG_PRIMARY_HOST: "mongodb-cfg"
      MONGODB_CFG_REPLICA_SET_NAME: "cfgreplicaset"
      MONGODB_REPLICA_SET_KEY: "replicasetkey123"
      MONGODB_ROOT_PASSWORD: "password123"
    ports:
      - "27017:27017"

  mongodb-shard0:
    image: bitnami/mongodb-sharded:4.4
    restart: unless-stopped
    environment:
      MONGODB_ADVERTISED_HOSTNAME: "mongodb-shard0"
      MONGODB_SHARDING_MODE: "shardsvr"
      MONGODB_MONGOS_HOST: "mongodb-sharded"
      MONGODB_ROOT_PASSWORD: "password123"
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_REPLICA_SET_KEY: "replicasetkey123"
      MONGODB_REPLICA_SET_NAME: "shard0"

  mongodb-cfg:
    image: bitnami/mongodb-sharded:4.4
    restart: unless-stopped
    environment:
      MONGODB_ADVERTISED_HOSTNAME: "mongodb-cfg"
      MONGODB_SHARDING_MODE: "configsvr"
      MONGODB_ROOT_PASSWORD: "password123"
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_REPLICA_SET_KEY: "replicasetkey123"
      MONGODB_REPLICA_SET_NAME: "cfgreplicaset"

  ratus:
    image: hyperonym/ratus:0.6.0
    restart: unless-stopped
    depends_on:
      - mongodb-sharded
    environment:
      ENGINE: "mongodb"
      MONGODB_URI: "mongodb://root:password123@mongodb-sharded:27017"
      MONGODB_DATABASE: "ratus"
      MONGODB_COLLECTION: "tasks"
      MONGODB_RETENTION_PERIOD: "72h"
    ports:
      - "8000:80"
